/**
 * WORKFORCEOS V-2 - CORE SYSTEM CONSTANTS
 * Defines core parameters, column indices, and operational constraints.
 */

const SYSTEM_CONFIG = {
  VERSION: "2.0.0",
  SESSION_TTL_MS: 43200000, // 12 Hours
  MAX_ATTACHMENT_SIZE_BYTES: 26214400, // 25 MB Cumulative
  MAX_IMAGE_SIZE_BYTES: 3145728,       // 3 MB Single
  MAX_PDF_SIZE_BYTES: 5242880,        // 5 MB Single
  MAX_ATTACHMENT_COUNT: 5
};

// Spreadsheet Sheet Name Constants
const SHEET_NAMES = {
  EMPLOYEE_MASTER: "EMPLOYEE_MASTER",
  TASK_LIST: "TASK_LIST",
  MY_TASKS: "MY_TASKS",
  TASK_HISTORY: "TASK_HISTORY",
  EMPLOYEE_SCORECARD: "EMPLOYEE_SCORECARD",
  SHIFT_MASTER: "SHIFT_MASTER",
  HOLIDAY_MASTER: "HOLIDAY_MASTER",
  LEAVE_TYPE_MASTER: "LEAVE_TYPE_MASTER",
  ATTENDANCE_LOGS: "ATTENDANCE_LOGS",
  ATTENDANCE_CORRECTIONS: "ATTENDANCE_CORRECTIONS",
  LEAVE_REQUESTS: "LEAVE_REQUESTS",
  SALARY_MASTER: "SALARY_MASTER",
  PAYROLL_RUN: "PAYROLL_RUN",
  ADVANCE_REQUESTS: "ADVANCE_REQUESTS",
  NOTIFICATIONS: "NOTIFICATIONS"
};

// Sheet-Wise Column Mapping Indexes (0-Based)
const COL_INDEX = {
  EMPLOYEE_MASTER: {
    EMP_ID: 0,
    NAME: 1,
    DESIGNATION: 2,
    DEPARTMENT: 3,
    MOBILE: 4,
    EMAIL: 5,
    DOB: 6,
    USERNAME: 7,
    PASSWORD: 8,
    AADHAR: 9,
    PAN: 10,
    BANK_ACCOUNT: 11,
    ADDRESS: 12,
    STATUS: 13,
    CREATED_BY: 14,
    CREATED_DATE: 15,
    UPDATED_BY: 16,
    UPDATED_DATE: 17,
    ROLE: 18,
    PHOTO_URL: 19,
    EMPLOYEE_TYPE: 20,
    REPORTING_MANAGER: 21
  },
  TASK_LIST: {
    TASK_NO: 0,
    TITLE: 1,
    DESCRIPTION: 2,
    ASSIGNED_BY_EMPID: 3,
    ASSIGNED_BY_NAME: 4,
    ASSIGNED_TO_EMPID: 5,
    ASSIGNED_TO_NAME: 6,
    DESIGNATION: 7,
    DEPARTMENT: 8,
    PRIORITY: 9,
    ASSIGN_DATE: 10,
    DUE_DATE: 11,
    STATUS: 12,
    COMPLETION_DATE: 13,
    REMARKS: 14,
    EXTENSION_REASON: 15,
    REQUESTED_DUE_DATE: 16,
    ORIGINAL_ASSIGNEE_EMPID: 17,
    ORIGINAL_ASSIGNEE_NAME: 18,
    RE_DELEGATED_BY_EMPID: 19,
    RE_DELEGATED_BY_NAME: 20,
    IS_RE_DELEGATED: 21,
    REVIEW_STATUS: 22,
    CONCERN_RAISED_BY_EMPID: 23,
    CONCERN_REASON: 24,
    PARENT_TASK_NO: 25,
    ATTACHMENT_DATA: 26,
    ATTACHMENT_COUNT: 27,
    ATTACHMENT_TOTAL_SIZE: 28
  },
  ATTENDANCE_LOGS: {
    ATTENDANCE_ID: 0,
    DATE: 1,
    EMP_ID: 2,
    EMPLOYEE_NAME: 3,
    DEPARTMENT: 4,
    DESIGNATION: 5,
    EMPLOYEE_TYPE: 6,
    SHIFT_ID: 7,
    CHECK_IN: 8,
    CHECK_OUT: 9,
    WORKING_HOURS: 10,
    LATE_MINUTES: 11,
    STATUS: 12,
    HOLIDAY_WORKED: 13,
    REMARKS: 14,
    CREATED_ON: 15
  },
  ATTENDANCE_CORRECTIONS: {
    CORRECTION_ID: 0,
    EMP_ID: 1,
    EMPLOYEE_NAME: 2,
    ATTENDANCE_DATE: 3,
    CURRENT_CHECKIN: 4,
    CURRENT_CHECKOUT: 5,
    REQUESTED_CHECKIN: 6,
    REQUESTED_CHECKOUT: 7,
    REASON: 8,
    ATTACHMENT_URI: 9,
    STATUS: 10,
    FORWARDED_TO: 11,
    APPROVED_BY: 12,
    APPROVED_ON: 13
  },
  LEAVE_REQUESTS: {
    REQUEST_ID: 0,
    EMP_ID: 1,
    EMPLOYEE_NAME: 2,
    DEPARTMENT: 3,
    LEAVE_TYPE: 4,
    FROM_DATE: 5,
    TO_DATE: 6,
    TOTAL_DAYS: 7,
    REASON: 8,
    ATTACHMENT_URL: 9,
    MANAGER_STATUS: 10,
    MANAGER_REMARKS: 11,
    HR_STATUS: 12,
    HR_REMARKS: 13,
    FINAL_STATUS: 14,
    APPLIED_ON: 15
  },
  SALARY_MASTER: {
    EMP_ID: 0,
    EMPLOYEE_NAME: 1,
    DEPARTMENT: 2,
    DESIGNATION: 3,
    BASIC_SALARY: 4,
    HRA: 5,
    CONVEYANCE: 6,
    OTHER_ALLOWANCE: 7,
    PF_APPLICABLE: 8,
    ESI_APPLICABLE: 9,
    BANK_NAME: 10,
    ACCOUNT_NUMBER: 11,
    IFSC: 12,
    STATUS: 13,
    CL_ALLOWED: 14,
    SL_ALLOWED: 15,
    EL_ALLOWED: 16,
    CL_USED: 17,
    SL_USED: 18,
    EL_USED: 19,
    LWP_USED: 20
  }
};

// System Roles Matrix
const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  HR: "HR",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE"
};
